sudo: required
services:
  - docker

before_install:
  - docker build -t shomarov/fibonacci-calculator-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shomarov/fibonacci-calculator-test npm run test

after_success:
  - docker build -t shomarov/fibonacci-calculator-client ./client
  - docker build -t shomarov/fibonacci-calculator-nginx ./nginx
  - docker build -t shomarov/fibonacci-calculator-server ./server
  - docker build -t shomarov/fibonacci-calculator-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shomarov/fibonacci-calculator-client
  - docker push shomarov/fibonacci-calculator-nginx
  - docker push shomarov/fibonacci-calculator-server
  - docker push shomarov/fibonacci-calculator-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: fibonacci-calculator
  env: DockerComplexPractice-env
  bucket_name: elasticbeanstalk-eu-central-1-801956187188
  bucket_path: fibonacci-calculator
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
